### ISSUE TITLE
Why <space>?

### ISSUE THREAD

**Issue by s0lst1ce** [yoav-lavi/melody#20]
I don't understand why there's `<space>` instead of `" "`?

**Comment by yoav-lavi** [comment]
Hey @s0lst1ce, thanks for the feedback. 

There's a general discussion around symbol syntax (https://github.com/yoav-lavi/melody/discussions/6), but I'm assuming you're asking why specifically have a symbol for space. The reason is that `<space>` compiles into `\s` in regex which matches whitespace, specifically the following:

- A space character
- A tab character
- A carriage return character
- A new line character
- A vertical tab character
- A form feed character

(source: https://www.w3schools.com/jsref/jsref_regexp_whitespace.asp)

Whereas `" "` would only match a literal space character. In some cases they'd be interchangeable but not always.

That being said, if you only need to match space, you're completely free to use `" "` (or even just end / start a literal with a space)

If you think `<space>` isn't clear (the naming itself), let me know and I'll consider whether it needs to be changed.

Hopefully this helps!

**Comment by s0lst1ce** [comment]
I see. I would indeed prefer itbto be renamed <whitedpace> since that's what it actually is.
Thanks for the explanation BTW.
