### ISSUE TITLE
Boolean OR

### ISSUE THREAD

**Issue by Myzel394** [yoav-lavi/melody#96]
**Describe the solution you'd like**
A way to express boolean or `|`.

Example:

```
"a" or "b";
(some of <digit>) or (some of <word>) or (some of <digit>)
```

**Additional context**
is this project even maintained?

**Comment by diversable** [comment]
> **Describe the solution you'd like** A way to express boolean or `|`.
> 
> Example:
> 
> ```
> "a" or "b";
> (some of <digit>) or (some of <word>) or (some of <digit>)
> ```

-> Proposal seconded!

> 
> **Additional context** is this project even maintained?

-> I just checked the original developer's gh page and noticed that he's from Israel; so, he may be otherwise occupied atm (?). 
@Myzel394: If you're interested in forking this project - with the intention to merge back into this repo if/when the original dev reappears - please open a new issue with the link to your fork. I'll try to contribute if I can, but I can't currently make guarantees (b/c of some persistent, annoying health issues). Thx!

**Comment by yoav-lavi** [comment]
Hey!

RE the project being maintained - It's not abandoned and I do update it once in a while, but due to also having a full time job / additional projects and other responsibilities it's not necessarily as often or as quickly as projects with dedicated teams.

I'd be happy to accept a PR for this feature, or otherwise I could implement it sometime in the near future (can't currently guarantee an exact time though).

I'd be happy to hear what you're using Melody for if you're willing to share - While this repo seems to be getting a fair bit of interest I actually have very little idea of the specific usage numbers / use cases in the wild.

Thanks!

**Comment by Myzel394** [comment]
> I'd be happy to hear what you're using Melody for if you're willing to share - While this repo seems to be getting a fair bit of interest I actually have very little idea of the specific usage numbers / use cases in the wild.

In our case we want a regex that matches human typed URLs in a given text. So that means we can not expect everyday users to type in "https://" for example, or use colons, quotation marks or other characters correctly. So far, we are using a very long regex at the moment. I was thinking about switching to melody because the regex is kinda hard to read. However, for this feature I'd need boolean OR, and imports would also be very useful here, as we periodically hardcode all available top level domains.

No worries though, the regex is working fine at the moment :D

**Comment by yoav-lavi** [comment]
@Myzel394 now that I'm taking another look at this issue, doesn't `either` cover this?

```
either {
  some of <word>;
  some of <digit>;
}
```

Which would produce

```regex
(:?\w+:\d+)
```

Same with the first example:

```
either {
  "a";
  "b";
}
```

Would result in

```regex
(?:a|b)
```

As far as I understand this should achieve what you're trying to do, so closing this for now. If I misunderstood  feel free to reopen with a clarification.
